#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

#!/bin/bash

# Update package list
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
server_config="
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 176572-web01 3.90.81.88:80 check
    server 176572-web02 100.25.199.115:80 check
"

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to start by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Testing the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

